services:

  frontend:
    build: ./Frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    
  backend: 
    build: ./Backend
    container_name: backend

    depends_on:
      - redis
    restart: unless-stopped
    environment:
      - NODE_ENV=production
  
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
  judge-service: 
    build: ./judge_Service
    container_name: judge
    volumes:
      - ./judge_Service:/judge_Service
      - /judge_Service/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
    restart: unless-stopped
    environment:
      - NODE_ENV=production
  