FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    g++ \
    python3 \
    nodejs \
    npm \
    default-jdk \
    time && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

CMD ["bash"]   